name: Uploading Artifacts Workflow

on:
    workflow_dispatch:

jobs:
    uploading-artifact-file:
        runs-on: Ubuntu-latest
        steps:
            - name: Creating two files
              run: |
                mkdir -p path/to/artifact
                echo "My name is qaiser ali" >> path/to/artifact/qaiser.txt
                echo "I am learning GitHub actions" >> path/to/artifact/actions.txt

            - name: Uploading the artifacts
              uses: actions/upload-artifact@v3
              with: 
                name: Artifact-Experimenting
                # Upload from the root to include the full 'path/to/artifact' structure in the artifact
                path: path

    Downloading-artifacts:
        runs-on: ubuntu-latest
        needs: uploading-artifact-file
        steps:
            - name: Download a Build Artifact
              uses: actions/download-artifact@v2.1.1
              with:
                name: Artifact-Experimenting
                # Specify a directory for download to preserve the structure
                path: downloaded-artifacts
            
            - name: Viewing the artifacts content
              run: |
                ls -R downloaded-artifacts
                cat downloaded-artifacts/path/to/artifact/qaiser.txt
                cat downloaded-artifacts/path/to/artifact/actions.txt
