name: Working with Cache

on:
    workflow_dispatch:

jobs:
    cache-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v3
              env:
                 cache-name: go-cache
              with:
              path: |
                ~/.cache/go-build
                ~/go/pkg/mod
              key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
              restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

# this is just an example on how to use cache system, to actually run this you need files such as golang to execute and test it