name: Create Issue using GitHub Actions

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Issue
        run: |
          # Use the GITHUB_TOKEN secret to authenticate with the GitHub API
          curl -X POST -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "Testing new issue",
              "body": "This is the issue description of the test issue which we have created"
            }'